apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-quizdb.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql-quizdb.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mysql-quizdb.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-quizdb.fullname" . }}-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-quizdb.fullname" . }}-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-quizdb.fullname" . }}-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ include "mysql-quizdb.fullname" . }}-pvc
