apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-quizdb.fullname" . }}-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword }}
  mysql-user: {{ .Values.mysql.user }}
  mysql-password: {{ .Values.mysql.password }}
