apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-quizdb.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mysql-quizdb.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
