replicaCount: 1

image:
  repository: manoharshetty507/quiz-web-app
  tag: v1
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30005

env:
  SQLALCHEMY_DATABASE_URI: mysql://quiz-user:password@mysql-quizdb-service:3306/quizdb
