apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quiz-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quiz-app.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quiz-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: quiz-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: {{ .Values.env.SQLALCHEMY_DATABASE_URI | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
