apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiz-app.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quiz-app.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
